# Generated by Django 4.2 on 2023-04-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_featured_product_popular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='featured',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='popular',
            field=models.BooleanField(),
        ),
    ]
